### ISSUE TITLE
{"detail":"No devices connected"}  after some time

### ISSUE THREAD

**Issue by fczuardi** [lnbits/jukebox#15]
I still don't have a super reproducible test case for this, but I noticed that sometimes the "device" information is lost and when that happens I cannot even reconfigure an existing jukebox to set device + playlists.

I will try to investigate more what happens and update this issue with what I gather

**Comment by fczuardi** [comment]
something related with the spotify token maybe?

do they expire? is our renovation code ok? I will take a look

**Comment by talvasconcelos** [comment]
Yes, the access token expires in 1 hour, i think the logic for renew is not working straight!
