### ISSUE TITLE
LNBits JukeBox - Add song search box and page arrows for playlists longer than 100 songs

### ISSUE THREAD

**Issue by CryptoCloaks** [lnbits/jukebox#4]
Hey!

So we're setting up a Jukebox for the shop and we allowed the community to add songs to the "Shop Radio"
We ran into an issue. After 100 songs there's no way for someone to choose their song to play as it only shows the first 100.

A search box to search all songs on the list to pick one would be fantastic.
Also page arrows to allow you to scroll to the next 100 songs etc on the playlist.

If this can be done you guys rock! It's already hilarious watching people control the radio!
Much love
Rick 
CryptoCloaks

**Comment by talvasconcelos** [comment]
Sorry for taking so long to tackle this issue. Spotify limits the request to 100 tracks per playlist, and no more requests are made from LNbits. I'm working on it
