### ISSUE TITLE
validation error: juke_id field required (type=value_error.missing)

### ISSUE THREAD

**Issue by Uter1007** [lnbits/jukebox#5]
When using the 0.0.22 version on step (2. Add API keys) I get the following 400 Error.

Url: /jukebox/api/v1/jukebox

Payload:
`{
  price: "300",
  sp_secret: "549c8cc0edc74c2xxxxxxxxx",
  sp_user: "ce5c9dfc9f5d4e298yyyyyyy",
  title: "test",
  user: "12d4249ae0384ac7b87zzzzz",
  wallet: "440bbead02344ooooooooo"
}`

Response:
`{
    "detail": "1 validation error for Request\nquery -> juke_id\n  field required (type=value_error.missing)"
}`

**Comment by dni** [comment]
hey, thanks for this issue, the current version on our vetted repo is 0.2.2 did you mean that?

i looked through the code and improved it a bit, can you maybe try that pr?

**Comment by Uter1007** [comment]
works like a charm ;) thx
